import type { DimensionId } from "./metric-definitions";
import type { HospitalMetricCatalogItem } from "./hospital-metric-catalog";

export const COMPREHENSIVE_MONITORING_VERSION = "COMPREHENSIVE-MONITORING-2026.08.11.1";

export const COMPREHENSIVE_MONITORING_CODE_PREFIX = "hospital.monitor.";

/**
 * “全面监测”专业分析模板：客户规格中的五大类 30 项指标。
 * 基础指标描述取数口径；派生指标额外携带 formulaExpr，只引用本目录编码，
 * 由 app/metric-formula.ts 的安全引擎计算。readiness 按数据准备现状诚实标注：
 * 绝大多数需要先完成字段映射（configure），不能假装开箱即有真实数据。
 */
export const comprehensiveMonitoringCatalog: readonly HospitalMetricCatalogItem[] = [
  // ── 设备效益（economic，按单类/台设备） ──────────────────────────────
  {
    sourceItem: 1,
    code: "hospital.monitor.revenue",
    name: "设备收入",
    dimension: "economic",
    definition: "统计期内可唯一归属到单类/台设备的检查、治疗直接收入，扣除退费与冲销。",
    formula: "SUM(valid_charge_amount) - SUM(refund_amount)",
    numerator: "有效直接收费净额",
    denominator: "—",
    unit: "万元",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "科室", "项目", "月份"],
    sources: ["HIS/收费", "财务核算", "设备项目映射"],
    owner: "财务部确认；信息部映射；医学装备部复核设备归属",
    evidence: "partial",
    readiness: "configure",
    audience: ["leadership", "operations"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "收入必须绑定唯一设备；退费与冲销不得重复扣减。",
    decision: "沿用医院基线的有效收费净额口径，作为效益类派生指标的唯一收入来源。",
  },
  {
    sourceItem: 2,
    code: "hospital.monitor.cost",
    name: "设备成本",
    dimension: "economic",
    definition: "折旧、维修维保、直接人工、直接耗材、能耗及经医院确认的其他可控直接成本之和。",
    formula: "depreciation + repair_maintenance + direct_labor + direct_consumables + utilities + other_direct_cost",
    numerator: "可控直接成本分项之和",
    denominator: "—",
    unit: "万元",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "科室", "成本项目", "月份"],
    sources: ["财务/HRP", "SPD", "人力", "后勤能耗", "维修工单"],
    owner: "财务部牵头；医学装备部、人力、后勤会签",
    evidence: "industry",
    readiness: "configure",
    audience: ["leadership", "operations"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "维修与维保分开；人工分摊规则和能耗估算方法必须版本化。",
    decision: "报告必须注明是可控直接成本口径，不得冒充全成本。",
  },
  {
    sourceItem: 3,
    code: "hospital.monitor.profit",
    name: "设备利润",
    dimension: "economic",
    definition: "同一期间、同一设备范围内的设备收入减去设备成本。",
    formula: "设备收入 - 设备成本（同期间、同成本口径）",
    formulaExpr: "hospital.monitor.revenue - hospital.monitor.cost",
    numerator: "设备收入净额",
    denominator: "—",
    unit: "万元",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "科室", "月份"],
    sources: ["平台计算", "发布收入版本", "发布成本版本"],
    owner: "财务部复核",
    evidence: "partial",
    readiness: "configure",
    audience: ["leadership", "operations"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "收入与成本必须使用相同期间、设备范围和版本；任一缺失即不可计算。",
    decision: "派生指标由公式引擎计算，任何输入缺失时显式标记不可计算。",
  },
  {
    sourceItem: 4,
    code: "hospital.monitor.revenue_per_exam",
    name: "次均收入",
    dimension: "economic",
    definition: "设备收入除以同期去重检查人次。",
    formula: "设备收入 ÷ 检查人次",
    formulaExpr: "hospital.monitor.revenue / hospital.monitor.exam_count",
    numerator: "设备收入净额",
    denominator: "同期去重检查人次",
    unit: "万元/人次",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "科室", "月份"],
    sources: ["平台计算"],
    owner: "财务部/使用科室",
    evidence: "partial",
    readiness: "configure",
    audience: ["leadership", "operations"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "分母为 0 时显示不可计算，不得回填默认值。",
    decision: "分子分母必须同期间、同设备范围；除零显式失败。",
  },
  {
    sourceItem: 5,
    code: "hospital.monitor.cost_per_exam",
    name: "次均成本",
    dimension: "economic",
    definition: "设备成本除以同期去重检查人次。",
    formula: "设备成本 ÷ 检查人次",
    formulaExpr: "hospital.monitor.cost / hospital.monitor.exam_count",
    numerator: "设备可控直接成本",
    denominator: "同期去重检查人次",
    unit: "万元/人次",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "科室", "月份"],
    sources: ["平台计算"],
    owner: "财务部/使用科室",
    evidence: "partial",
    readiness: "configure",
    audience: ["leadership", "operations"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "分母为 0 时显示不可计算；成本口径必须与次均收入一致。",
    decision: "与次均收入成对展示，两者共用同一分母版本。",
  },
  {
    sourceItem: 6,
    code: "hospital.monitor.payback_years",
    name: "预计回收成本时间",
    dimension: "economic",
    definition: "设备购置投入按年度现金贡献回收的估算年数。",
    formula: "device_investment / annual_cash_contribution",
    numerator: "设备购置投入",
    denominator: "年度现金贡献（不含折旧）",
    unit: "年",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "科室", "年度"],
    sources: ["HRP/资产卡片", "财务核算", "平台计算"],
    owner: "财务部确认现金流口径",
    evidence: "industry",
    readiness: "configure",
    audience: ["leadership"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "年度现金贡献 ≤ 0 时不得计算；不能用含折旧净收益替代现金流。",
    decision: "回收期只用现金贡献口径，估算参数随报告冻结。",
  },
  {
    sourceItem: 7,
    code: "hospital.monitor.roi_rate",
    name: "投资回报率",
    dimension: "economic",
    definition: "年度设备净收益相对购置投入的比例。",
    formula: "annual_operating_surplus / device_investment * 100%",
    numerator: "年度设备净收益",
    denominator: "设备购置投入",
    unit: "%",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "科室", "年度"],
    sources: ["HRP/资产卡片", "财务核算", "平台计算"],
    owner: "财务部/资产管理部门",
    evidence: "industry",
    readiness: "configure",
    audience: ["leadership"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "投入为 0 或负数时不计算；净收益口径（含/不含折旧）必须标注。",
    decision: "与回收期分别核算，不允许在两种收益口径之间静默切换。",
  },
  // ── 设备效率（efficiency，按单类/台设备） ────────────────────────────
  {
    sourceItem: 8,
    code: "hospital.monitor.exam_count",
    name: "检查人次",
    dimension: "efficiency",
    definition: "完成状态的检查按检查主键去重；一次检查含多部位仍计 1 人次。",
    formula: "COUNT_DISTINCT(examId) FILTER completed = true",
    numerator: "去重后的有效检查事实",
    denominator: "—",
    unit: "人次",
    grain: "hospital+examId+period",
    dimensions: ["医院", "设备", "科室", "项目", "月份"],
    sources: ["PACS/RIS", "HIS", "设备资产台账"],
    owner: "医务处/影像科确认；信息部实现",
    evidence: "direct",
    readiness: "ready",
    audience: ["leadership", "operations", "quality"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "多部位不得重复计人次；取消/作废报告不进入分子。",
    decision: "与平台 examId 去重模型一致，作为效益类派生指标的分母。",
  },
  {
    sourceItem: 9,
    code: "hospital.monitor.standard_workload",
    name: "标准工作量",
    dimension: "efficiency",
    definition: "考虑项目复杂度权重后的可比工作量。",
    formula: "SUM(item_count * item_weight)",
    numerator: "项目数量乘以项目权重之和",
    denominator: "—",
    unit: "点",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "科室", "项目", "月份"],
    sources: ["PACS/RIS/LIS", "项目权重字典"],
    owner: "医务处/绩效办定权重",
    evidence: "industry",
    readiness: "configure",
    audience: ["operations"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "项目权重必须版本化；权重缺失的项目进入待补队列而非按 1 处理。",
    decision: "权重表未发布前不出数，避免不同设备类别直接混比。",
  },
  {
    sourceItem: 10,
    code: "hospital.monitor.daily_peak_workload",
    name: "单日工作峰值",
    dimension: "efficiency",
    definition: "统计期内单台设备单个自然日完成检查人次的最大值。",
    formula: "MAX(daily_exam_count)",
    numerator: "单日去重检查人次最大值",
    denominator: "—",
    unit: "人次/日",
    grain: "hospital+device+day",
    dimensions: ["医院", "设备", "科室", "日期"],
    sources: ["PACS/RIS", "HIS"],
    owner: "运营部/使用科室",
    evidence: "partial",
    readiness: "configure",
    audience: ["operations"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "按医院业务日切分；跨日检查计入开始日。",
    decision: "峰值只做排班参考，不得直接作为额定产能。",
  },
  {
    sourceItem: 11,
    code: "hospital.monitor.effective_working_hours",
    name: "有效工作时长",
    dimension: "efficiency",
    definition: "设备实际执行检查/治疗任务的状态时长总和，不含空转和待机。",
    formula: "SUM(task_end_at - task_start_at)",
    numerator: "有效任务区间时长之和",
    denominator: "—",
    unit: "小时",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "科室", "日期", "班次"],
    sources: ["设备日志", "物联网", "PACS/RIS"],
    owner: "医学装备部确认状态；使用科室确认任务",
    evidence: "partial",
    readiness: "configure",
    audience: ["operations", "equipment"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "重叠区间去重；不得用开机时长替代有效时长。",
    decision: "与开机时长分开管理，空转必须显式暴露。",
  },
  // ── 临床使用质量（quality） ─────────────────────────────────────────
  {
    sourceItem: 12,
    code: "hospital.monitor.enhancement_rate",
    name: "检查增强率",
    dimension: "quality",
    definition: "适用检查中采用增强方案的占比，分母限定适用项目。",
    formula: "enhanced_exam_count / eligible_exam_count * 100%",
    numerator: "增强检查数",
    denominator: "适用检查总数",
    unit: "%",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "科室", "项目", "月份"],
    sources: ["PACS/RIS", "药耗记录"],
    owner: "影像科/质控办",
    evidence: "partial",
    readiness: "configure",
    audience: ["quality"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "分母必须限定适用项目；分母为 0 时不计算。",
    decision: "适用范围字典发布前不出数，避免跨项目误比。",
  },
  {
    sourceItem: 13,
    code: "hospital.monitor.positive_rate",
    name: "检查阳性率",
    dimension: "quality",
    definition: "阳性或疑似阳性的有效检查报告数占同期去重有效检查人次的比例。",
    formula: "positive_report_count / eligible_exam_count * 100%",
    numerator: "阳性或疑似阳性有效报告数",
    denominator: "同期去重有效检查人次",
    unit: "%",
    grain: "hospital+device+examId+period",
    dimensions: ["医院", "设备", "科室", "项目", "月份"],
    sources: ["PACS/RIS", "HIS"],
    owner: "医务处/质控办/影像科",
    evidence: "direct",
    readiness: "configure",
    audience: ["leadership", "quality"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "分子分母同一适用范围；多部位只计一次；不得跨设备类别直接排名。",
    decision: "阳性判定以影像报告结构化结论为准，需先完成报告字段映射。",
  },
  {
    sourceItem: 14,
    code: "hospital.monitor.positive_rate_by_patient_source",
    name: "按患者来源统计检查阳性率",
    dimension: "quality",
    definition: "阳性率按门诊、住院、急诊、体检等患者来源分组统计。",
    formula: "positive_report_count / eligible_exam_count * 100% GROUP BY patient_source",
    numerator: "分组内阳性或疑似阳性报告数",
    denominator: "分组内去重有效检查人次",
    unit: "%",
    grain: "hospital+device+patient_source+period",
    dimensions: ["医院", "设备", "患者来源", "月份"],
    sources: ["PACS/RIS", "HIS"],
    owner: "医务处/质控办",
    evidence: "partial",
    readiness: "configure",
    audience: ["quality"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "患者来源字典必须统一；来源缺失记录进入待补队列。",
    decision: "分组阳性率不参与总排名，只用于结构分析。",
  },
  {
    sourceItem: 15,
    code: "hospital.monitor.positive_rate_by_body_part",
    name: "按检查部位统计检查阳性率",
    dimension: "quality",
    definition: "阳性率按标准部位字典分组统计，检查—部位联合键去重。",
    formula: "positive_report_count / eligible_exam_count * 100% GROUP BY body_part",
    numerator: "分组内阳性或疑似阳性报告数",
    denominator: "分组内去重有效检查人次",
    unit: "%",
    grain: "hospital+device+bodyPart+period",
    dimensions: ["医院", "设备", "主部位", "月份"],
    sources: ["PACS/RIS", "标准部位字典"],
    owner: "医务处/影像科",
    evidence: "partial",
    readiness: "configure",
    audience: ["quality"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "同一检查同一部位去重；部位字典必须版本化。",
    decision: "部位分组不改变检查人次口径，金额分摊规则另行冻结。",
  },
  {
    sourceItem: 16,
    code: "hospital.monitor.positive_rate_by_order_dept",
    name: "按开单科室统计检查阳性率",
    dimension: "quality",
    definition: "阳性率按开单科室分组统计，用于合理检查行为分析。",
    formula: "positive_report_count / eligible_exam_count * 100% GROUP BY ordering_department",
    numerator: "分组内阳性或疑似阳性报告数",
    denominator: "分组内去重有效检查人次",
    unit: "%",
    grain: "hospital+device+ordering_department+period",
    dimensions: ["医院", "设备", "开单科室", "月份"],
    sources: ["PACS/RIS", "HIS"],
    owner: "医务处/质控办",
    evidence: "partial",
    readiness: "configure",
    audience: ["leadership", "quality"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "开单科室与执行科室分开；科室合并调整必须留痕。",
    decision: "结果仅用于合理用检提醒，不直接用于科室绩效排名。",
  },
  // ── 患者体验（experience） ──────────────────────────────────────────
  {
    sourceItem: 17,
    code: "hospital.monitor.total_journey_hours",
    name: "患者检查总时长",
    dimension: "experience",
    definition: "患者签到/到检至报告可获取的全流程平均耗时。",
    formula: "AVG(report_released_at - checkin_at)",
    numerator: "各检查全流程耗时之和",
    denominator: "有效检查数",
    unit: "小时",
    grain: "hospital+device+examId+period",
    dimensions: ["医院", "设备", "科室", "月份"],
    sources: ["HIS", "叫号系统", "PACS/RIS"],
    owner: "运营部",
    evidence: "partial",
    readiness: "configure",
    audience: ["leadership", "operations"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "起止时点必须可追溯；跨日流程按实际时间差计算。",
    decision: "总时长与分段时长并列展示，不得用分段之和替代实测总时长。",
  },
  {
    sourceItem: 18,
    code: "hospital.monitor.appointment_wait_days",
    name: "患者预约等候时长",
    dimension: "experience",
    definition: "预约申请到计划检查时间的平均时长。",
    formula: "AVG(scheduled_exam_at - appointment_created_at)",
    numerator: "各预约等候时长之和",
    denominator: "有效预约数",
    unit: "天",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "科室", "月份"],
    sources: ["预约平台", "HIS"],
    owner: "门诊部/运营部",
    evidence: "partial",
    readiness: "configure",
    audience: ["leadership", "operations"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "与现场等待拆分；取消后重约按新预约计算。",
    decision: "预约等候与现场等候不得合并成一个指标。",
  },
  {
    sourceItem: 19,
    code: "hospital.monitor.exam_duration_minutes",
    name: "患者检查时长",
    dimension: "experience",
    definition: "检查开始到检查结束的平均时长。",
    formula: "AVG(exam_end_at - exam_start_at)",
    numerator: "各检查时长之和",
    denominator: "有效检查数",
    unit: "分钟",
    grain: "hospital+device+examId+period",
    dimensions: ["医院", "设备", "科室", "项目", "月份"],
    sources: ["PACS/RIS", "设备日志"],
    owner: "使用科室",
    evidence: "partial",
    readiness: "configure",
    audience: ["operations"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "开始时间必须早于结束时间；异常时长进入隔离复核。",
    decision: "检查时长按项目类型分层展示，不做跨类型平均。",
  },
  {
    sourceItem: 20,
    code: "hospital.monitor.report_wait_hours",
    name: "报告等候时长",
    dimension: "experience",
    definition: "检查结束到报告发布可获取的平均时长。",
    formula: "AVG(report_released_at - exam_end_at)",
    numerator: "各报告等候时长之和",
    denominator: "有效报告数",
    unit: "小时",
    grain: "hospital+device+examId+period",
    dimensions: ["医院", "设备", "科室", "月份"],
    sources: ["PACS/RIS"],
    owner: "诊断科室",
    evidence: "partial",
    readiness: "configure",
    audience: ["leadership", "operations", "quality"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "以报告正式发布时点为准；补发报告不重置起点。",
    decision: "急诊与常规报告分开统计，不合并平均。",
  },
  // ── 设备保障（reliability） ─────────────────────────────────────────
  {
    sourceItem: 21,
    code: "hospital.monitor.warranty_status",
    name: "保修状态",
    dimension: "reliability",
    definition: "时点上设备的保修/维保覆盖状态（保修期内、全保合同、脱保等）。",
    formula: "LATEST(warranty_status) BY device",
    numerator: "—",
    denominator: "—",
    unit: "状态",
    grain: "hospital+device+snapshot_date",
    dimensions: ["医院", "设备", "维保类型", "日期"],
    sources: ["设备资产台账", "维保合同"],
    owner: "医学装备部",
    evidence: "direct",
    readiness: "ready",
    audience: ["equipment"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "状态取自维保合同有效期；到期未续约必须显示脱保。",
    decision: "状态型指标只做枚举统计，不折算成分数。",
  },
  {
    sourceItem: 22,
    code: "hospital.monitor.fault_rate",
    name: "故障率",
    dimension: "reliability",
    definition: "每 1000 运行小时发生的可归责故障次数。",
    formula: "fault_count / power_on_hours * 1000",
    numerator: "可归责故障次数",
    denominator: "运行时长（千小时）",
    unit: "次/千小时",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "科室", "月份"],
    sources: ["维修工单/CMMS", "设备日志"],
    owner: "医学装备部",
    evidence: "industry",
    readiness: "configure",
    audience: ["equipment"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "分母为 0 时不计算；不得使用无分母的故障百分比。",
    decision: "沿用标准化故障率口径，禁止直接展示“故障率 X%”。",
  },
  {
    sourceItem: 23,
    code: "hospital.monitor.fault_downtime_hours",
    name: "故障停机时间",
    dimension: "reliability",
    definition: "故障发生到修复验收恢复可用的累计时长，不含计划保养与校准。",
    formula: "SUM(restored_at - fault_started_at)",
    numerator: "故障不可用区间总时长",
    denominator: "—",
    unit: "小时",
    grain: "hospital+device+fault_event+period",
    dimensions: ["医院", "设备", "科室", "故障类型", "月份"],
    sources: ["维修工单", "设备日志"],
    owner: "医学装备部",
    evidence: "partial",
    readiness: "configure",
    audience: ["leadership", "equipment"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "计划停机单独分类；重复工单合并；以恢复验收时点结束。",
    decision: "与医院基线故障停机口径保持一致，等待备件时间计入停机。",
  },
  {
    sourceItem: 24,
    code: "hospital.monitor.fault_type_count",
    name: "故障类型",
    dimension: "reliability",
    definition: "按标准故障类型字典分组统计的故障事件数。",
    formula: "COUNT(fault_event) GROUP BY fault_type",
    numerator: "分组内故障事件数",
    denominator: "—",
    unit: "次",
    grain: "hospital+device+fault_type+period",
    dimensions: ["医院", "设备", "故障类型", "月份"],
    sources: ["维修工单/CMMS"],
    owner: "医学装备部",
    evidence: "partial",
    readiness: "configure",
    audience: ["equipment"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "故障类型字典必须版本化；未分类工单进入待补队列。",
    decision: "类型分布用于备件与预防策略，不并入故障率分子重复计数。",
  },
  {
    sourceItem: 25,
    code: "hospital.monitor.consumable_usage",
    name: "耗材使用统计",
    dimension: "reliability",
    definition: "统计期内设备关联耗材的领用数量与金额。",
    formula: "SUM(consumable_quantity), SUM(consumable_amount)",
    numerator: "设备关联耗材领用量/金额",
    denominator: "—",
    unit: "件/元",
    grain: "hospital+device+consumable+period",
    dimensions: ["医院", "设备", "耗材", "批次", "月份"],
    sources: ["SPD", "库房出入库"],
    owner: "物资/SPD 部门确认设备归属",
    evidence: "partial",
    readiness: "configure",
    audience: ["operations", "equipment"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "退库冲减；批次与设备绑定关系必须可追溯。",
    decision: "耗材统计与成本归集共用同一出库口径，避免双重计费。",
  },
  {
    sourceItem: 26,
    code: "hospital.monitor.repair_hours",
    name: "故障修复时间",
    dimension: "reliability",
    definition: "已修复故障从报修到修复验收的平均时长（MTTR）。",
    formula: "SUM(restored_at - reported_at) / repaired_fault_count",
    numerator: "已修复故障总修复时长",
    denominator: "已修复故障数",
    unit: "小时",
    grain: "hospital+device+fault_event+period",
    dimensions: ["医院", "设备", "服务商", "故障类型", "月份"],
    sources: ["维修工单/CMMS"],
    owner: "医学装备部",
    evidence: "industry",
    readiness: "configure",
    audience: ["equipment"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "仅统计已修复故障；未结工单不进入平均值。",
    decision: "与维修响应时间拆分，两者不得混用同一标签。",
  },
  {
    sourceItem: 27,
    code: "hospital.monitor.diagnostician_workload",
    name: "诊断医生工作量",
    dimension: "reliability",
    definition: "统计期内诊断医生出具有效报告的数量。",
    formula: "COUNT(valid_report) GROUP BY diagnostician",
    numerator: "有效报告数",
    denominator: "—",
    unit: "份",
    grain: "hospital+device+diagnostician+period",
    dimensions: ["医院", "设备", "诊断医生", "月份"],
    sources: ["PACS/RIS", "人力岗位表"],
    owner: "医务处/诊断科室",
    evidence: "partial",
    readiness: "configure",
    audience: ["operations"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "审核报告与书写报告分开计数；作废报告不计。",
    decision: "工作量仅按人次统计，绩效折算权重由绩效办另行发布。",
  },
  {
    sourceItem: 28,
    code: "hospital.monitor.technician_workload",
    name: "操作技师工作量",
    dimension: "reliability",
    definition: "统计期内操作技师完成有效检查的数量。",
    formula: "COUNT(valid_exam) GROUP BY technician",
    numerator: "有效检查数",
    denominator: "—",
    unit: "人次",
    grain: "hospital+device+technician+period",
    dimensions: ["医院", "设备", "操作技师", "班次", "月份"],
    sources: ["PACS/RIS", "排班系统"],
    owner: "使用科室",
    evidence: "partial",
    readiness: "configure",
    audience: ["operations"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "多技师协作按主操作人计 1 次；替班必须留痕。",
    decision: "与诊断医生工作量并列展示，口径互不替代。",
  },
  {
    sourceItem: 29,
    code: "hospital.monitor.qc_completion_rate",
    name: "质控完成率",
    dimension: "reliability",
    definition: "按计划应执行的设备质控项目中实际完成的比例。",
    formula: "completed_qc_count / planned_qc_count * 100%",
    numerator: "已完成质控项目数",
    denominator: "计划质控项目数",
    unit: "%",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "质控项目", "月份"],
    sources: ["质控系统", "CMMS/EAM"],
    owner: "质控办/医学装备部",
    evidence: "industry",
    readiness: "configure",
    audience: ["quality", "equipment"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "计划数以发布的质控计划为准；补做质控单独标注。",
    decision: "完成率与通过率分开核算，不得合并成一个百分比。",
  },
  {
    sourceItem: 30,
    code: "hospital.monitor.pm_first_pass_rate",
    name: "PM一次性通过率",
    dimension: "reliability",
    definition: "已完成预防性维护中首次验收即通过的比例。",
    formula: "first_pass_pm_count / completed_pm_count * 100%",
    numerator: "首次验收通过的 PM 数",
    denominator: "已完成 PM 数",
    unit: "%",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "服务商", "月份"],
    sources: ["CMMS/EAM"],
    owner: "医学装备部",
    evidence: "industry",
    readiness: "configure",
    audience: ["equipment"],
    version: COMPREHENSIVE_MONITORING_VERSION,
    validation: "返工后通过不计入分子；分母为 0 时不计算。",
    decision: "与 PM 完成率拆分为两个指标，避免掩盖返工。",
  },
] as const;

export type ComprehensiveMonitoringCategory = {
  dimension: DimensionId;
  title: string;
  metricCodes: string[];
};

const categoryTitles: Array<{ dimension: DimensionId; title: string }> = [
  { dimension: "economic", title: "设备效益" },
  { dimension: "efficiency", title: "设备效率" },
  { dimension: "quality", title: "临床使用质量" },
  { dimension: "experience", title: "患者体验" },
  { dimension: "reliability", title: "设备保障" },
];

export const comprehensiveMonitoringCategories: ComprehensiveMonitoringCategory[] = categoryTitles.map(
  ({ dimension, title }) => ({
    dimension,
    title,
    metricCodes: comprehensiveMonitoringCatalog
      .filter((item) => item.dimension === dimension)
      .map((item) => item.code),
  }),
);

export const comprehensiveMonitoringCodes: ReadonlySet<string> = new Set(
  comprehensiveMonitoringCatalog.map((item) => item.code),
);
