import type { DimensionId } from "./metric-definitions";

export type HospitalMetricEvidence = "direct" | "partial" | "industry" | "incomplete";
export type HospitalMetricReadiness = "ready" | "configure" | "deferred";
export type HospitalMetricAudience = "leadership" | "operations" | "equipment" | "quality";

export type HospitalMetricCatalogItem = {
  sourceItem: number;
  code: string;
  name: string;
  dimension: DimensionId;
  definition: string;
  formula: string;
  numerator: string;
  denominator: string;
  unit: string;
  grain: string;
  dimensions: string[];
  sources: string[];
  owner: string;
  evidence: HospitalMetricEvidence;
  readiness: HospitalMetricReadiness;
  audience: HospitalMetricAudience[];
  version: string;
  validation: string;
  decision: string;
};

export const HOSPITAL_METRIC_CATALOG_VERSION = "HOSPITAL-BASELINE-2026.08.11.1";

/**
 * Hospital baseline derived from “医院设备管理指标计算口径与理论依据分析.xlsx”.
 * Ambiguous “or” formulas are deliberately split into separate metrics so a
 * published report never changes denominator silently between device types.
 */
export const hospitalMetricCatalog: readonly HospitalMetricCatalogItem[] = [
  {
    sourceItem: 1,
    code: "hospital.device.net_direct_revenue",
    name: "医院设备总收入",
    dimension: "economic",
    definition: "统计期内已完成且可唯一归属到设备的检查、治疗和设备操作直接收入，扣除退费与冲销；间接带动收入单列。",
    formula: "SUM(valid_charge_amount) - SUM(refund_amount)",
    numerator: "有效直接收费净额",
    denominator: "—",
    unit: "万元",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "科室", "项目", "月份"],
    sources: ["HIS/收费", "财务核算", "设备项目映射"],
    owner: "财务部确认；信息部映射；医学装备部复核设备归属",
    evidence: "partial",
    readiness: "configure",
    audience: ["leadership", "operations"],
    version: HOSPITAL_METRIC_CATALOG_VERSION,
    validation: "收入必须绑定唯一设备；退费与冲销不重复；同比/环比分别配置变化额和变化率。",
    decision: "采用 HIS 有效收费净额为主口径；“本期-同期”只叫变化额，变化率另建指标。",
  },
  {
    sourceItem: 2,
    code: "hospital.device.controllable_direct_cost",
    name: "医院设备可控直接成本",
    dimension: "economic",
    definition: "折旧、维修、维保、设备直接人员、直接耗材、水电气及经医院确认的其他可控直接成本。",
    formula: "depreciation + repair + maintenance + direct_labor + direct_consumables + utilities + other_controllable_direct_cost",
    numerator: "可控直接成本分项之和",
    denominator: "—",
    unit: "万元",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "科室", "成本项目", "月份"],
    sources: ["财务/HRP", "HIS", "SPD", "人力", "后勤能耗", "维修工单"],
    owner: "财务部牵头；医学装备部、人力、后勤和使用科室会签",
    evidence: "industry",
    readiness: "configure",
    audience: ["leadership", "operations"],
    version: HOSPITAL_METRIC_CATALOG_VERSION,
    validation: "维修与维保分开；合同内维修不重复；人工分摊规则和能耗估算方法必须版本化。",
    decision: "工作簿依据支持的是可控直接成本，不能直接冒充全成本；平台保留“全成本”作为另一口径。",
  },
  {
    sourceItem: 3,
    code: "hospital.device.operating_surplus",
    name: "医院设备总结余（设备盈余）",
    dimension: "economic",
    definition: "设备直接收入减去同一成本范围下的设备成本。",
    formula: "net_direct_revenue - selected_cost_scope",
    numerator: "设备总结余",
    denominator: "—",
    unit: "万元",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "科室", "月份"],
    sources: ["平台计算", "发布收入版本", "发布成本版本"],
    owner: "财务部复核",
    evidence: "partial",
    readiness: "configure",
    audience: ["leadership", "operations"],
    version: HOSPITAL_METRIC_CATALOG_VERSION,
    validation: "收入和成本必须使用相同期间、设备范围、权责/收付口径和版本。",
    decision: "报告中必须注明是“可控直接结余”还是“全成本结余”，两者不能混用。",
  },
  {
    sourceItem: 4,
    code: "hospital.device.exam_count",
    name: "医院设备总检查人次",
    dimension: "efficiency",
    definition: "完成状态的检查按检查主键/报告事实去重；一次检查含多个部位仍计 1 人次，并剔除体检。",
    formula: "COUNT_DISTINCT(examId) FILTER completed = true AND physical_exam = false",
    numerator: "去重后的有效检查事实",
    denominator: "—",
    unit: "人次",
    grain: "hospital+examId+period",
    dimensions: ["医院", "设备", "科室", "项目", "月份"],
    sources: ["PACS/RIS", "HIS", "设备资产台账"],
    owner: "医务处/影像科确认；信息部实现",
    evidence: "direct",
    readiness: "ready",
    audience: ["leadership", "operations", "quality"],
    version: HOSPITAL_METRIC_CATALOG_VERSION,
    validation: "多部位不得重复计人次；体检识别规则必须可追溯；取消/作废报告不进入分子。",
    decision: "与当前平台 examId 去重和多部位模型完全一致，作为首批核心指标。",
  },
  {
    sourceItem: 5,
    code: "hospital.device.body_part_service_count",
    name: "医院设备检查部位服务量",
    dimension: "quality",
    definition: "按检查—部位联合键统计的部位服务量，用于结构分析，不等同于检查人次。",
    formula: "COUNT_DISTINCT(examId, bodyPart)",
    numerator: "去重检查—部位关联数",
    denominator: "—",
    unit: "部位次",
    grain: "hospital+examId+bodyPart+period",
    dimensions: ["医院", "设备", "科室", "主部位", "全部部位", "月份"],
    sources: ["PACS/RIS", "标准部位字典"],
    owner: "医务处/影像科确认；信息部实现",
    evidence: "incomplete",
    readiness: "configure",
    audience: ["operations", "quality"],
    version: HOSPITAL_METRIC_CATALOG_VERSION,
    validation: "同一检查同一部位去重；收入和成本不得按部位行复制，必须使用冻结的分摊规则。",
    decision: "将原“检查部位数”改名为“部位服务量”，先补齐来源、字典和用途再启用。",
  },
  {
    sourceItem: 6,
    code: "hospital.device.power_on_hours",
    name: "医院设备总开机时长",
    dimension: "efficiency",
    definition: "统计期内设备处于上电状态的去重时间区间总和，包含空转，不包含关机。",
    formula: "SUM(DISTINCT_INTERVAL_DURATION(power_on_intervals))",
    numerator: "去重后的上电状态时长",
    denominator: "—",
    unit: "小时",
    grain: "hospital+device+state_interval+period",
    dimensions: ["医院", "设备", "科室", "日期", "班次"],
    sources: ["设备本机日志", "物联网", "运维监控"],
    owner: "医学装备部确认状态码；信息部/物联网团队采集",
    evidence: "partial",
    readiness: "configure",
    audience: ["operations", "equipment"],
    version: HOSPITAL_METRIC_CATALOG_VERSION,
    validation: "重复心跳不累加；跨日区间切分；时区一致；明确上电、待机、作业和关机状态。",
    decision: "能效标签只用于功率/能耗参数，开机时长仍以设备日志或采集网关为准。",
  },
  {
    sourceItem: 7,
    code: "hospital.device.time_utilization_rate",
    name: "设备时间使用率",
    dimension: "efficiency",
    definition: "设备实际用于诊疗的时长相对计划可服务时长的比例。",
    formula: "active_clinical_hours / scheduled_service_hours * 100%",
    numerator: "实际诊疗时长",
    denominator: "计划可服务时长",
    unit: "%",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "科室", "月份"],
    sources: ["PACS/RIS/业务事件", "设备日志", "排班计划"],
    owner: "运营部/使用科室确认计划；医学装备部确认状态",
    evidence: "partial",
    readiness: "configure",
    audience: ["leadership", "operations", "equipment"],
    version: HOSPITAL_METRIC_CATALOG_VERSION,
    validation: "计划停机应从分母扣除；实际诊疗时长不能用开机时长替代。",
    decision: "把工作簿中的两个“或”公式拆开；本指标只采用时间分母。",
  },
  {
    sourceItem: 7,
    code: "hospital.device.capacity_utilization_rate",
    name: "设备产能利用率",
    dimension: "efficiency",
    definition: "实际工作量相对设备类别与排班共同确定的额定可完成工作量的比例。",
    formula: "actual_weighted_workload / rated_workload_for_period * 100%",
    numerator: "实际标准工作量",
    denominator: "单日额定标准工作量 × 有效开放天数",
    unit: "%",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "设备类别", "科室", "月份"],
    sources: ["PACS/RIS/LIS", "设备类别产能参数", "排班计划"],
    owner: "医务处/运营部/使用科室确认额定产能",
    evidence: "partial",
    readiness: "configure",
    audience: ["operations", "equipment"],
    version: HOSPITAL_METRIC_CATALOG_VERSION,
    validation: "设备类别和项目复杂度不同，应使用标准工作量；额定产能必须按版本和生效日期管理。",
    decision: "与时间使用率并列展示，不允许系统在两个分母之间自动切换。",
  },
  {
    sourceItem: 8,
    code: "hospital.device.avg_service_count_per_active_device",
    name: "台均服务人次",
    dimension: "efficiency",
    definition: "同类设备去重检查人次除以统计期内有效在用设备台数，剔除体检。",
    formula: "exam_count / active_device_count",
    numerator: "同类设备去重检查人次",
    denominator: "统计期有效在用设备台数",
    unit: "人次/台",
    grain: "hospital+device_category+period",
    dimensions: ["医院", "设备类别", "科室", "月份"],
    sources: ["PACS/RIS", "设备资产台账"],
    owner: "医学装备部/运营部",
    evidence: "industry",
    readiness: "deferred",
    audience: ["operations"],
    version: HOSPITAL_METRIC_CATALOG_VERSION,
    validation: "分母按在用天数加权；新增、停用、调拨设备不能简单按期末台数计算。",
    decision: "遵循工作簿备注“先搁置”，保留定义但不进入首版院长驾驶舱。",
  },
  {
    sourceItem: 9,
    code: "hospital.device.avg_daily_active_hours",
    name: "日均工作时长",
    dimension: "efficiency",
    definition: "设备实际诊疗总时长按已配置日基准平均。",
    formula: "active_clinical_hours / configured_day_count",
    numerator: "实际诊疗总时长",
    denominator: "日历天数或有效开放天数（必须显式配置）",
    unit: "小时/日",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "科室", "月份"],
    sources: ["PACS/RIS", "设备日志", "医院日历/排班"],
    owner: "运营部/使用科室确认日基准",
    evidence: "industry",
    readiness: "configure",
    audience: ["operations", "equipment"],
    version: HOSPITAL_METRIC_CATALOG_VERSION,
    validation: "院级汇总应先按设备求和再除以设备有效日，不能把多台设备总时长只除一次日历天数。",
    decision: "工作簿采用日历天数；平台增加“日历日/开放日”口径参数并在报告中展示。",
  },
  {
    sourceItem: 10,
    code: "hospital.device.avg_daily_power_on_hours",
    name: "日均开机时长",
    dimension: "efficiency",
    definition: "设备上电总时长按已配置日基准平均，包含空转。",
    formula: "power_on_hours / configured_day_count",
    numerator: "开机通电总时长",
    denominator: "日历天数或有效开放天数（必须显式配置）",
    unit: "小时/日",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "科室", "月份"],
    sources: ["设备本机日志", "物联网", "医院日历/排班"],
    owner: "医学装备部/运营部",
    evidence: "partial",
    readiness: "configure",
    audience: ["operations", "equipment"],
    version: HOSPITAL_METRIC_CATALOG_VERSION,
    validation: "日均值不应超过 24 小时；院级汇总分母需乘以设备有效日。",
    decision: "与日均工作时长成对展示，显式揭示开机空转。",
  },
  {
    sourceItem: 11,
    code: "hospital.device.work_saturation_rate",
    name: "工作饱和度",
    dimension: "efficiency",
    definition: "设备开机时段中实际用于诊疗的时间占比。",
    formula: "active_clinical_hours / power_on_hours * 100%",
    numerator: "实际诊疗总时长",
    denominator: "开机总时长",
    unit: "%",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "科室", "月份", "班次"],
    sources: ["PACS/RIS", "设备日志", "物联网"],
    owner: "运营部/医学装备部",
    evidence: "industry",
    readiness: "ready",
    audience: ["leadership", "operations", "equipment"],
    version: HOSPITAL_METRIC_CATALOG_VERSION,
    validation: "分母为 0 时显示不可计算；实际诊疗时长不得大于开机时长。",
    decision: "等同平台现有“负荷率”，保留医院名称作为展示别名。",
  },
  {
    sourceItem: 12,
    code: "hospital.device.fleet_good_condition_rate",
    name: "设备完好率",
    dimension: "reliability",
    definition: "时点上技术性能良好且可正常使用的在用设备台数占在用设备总台数的比例。",
    formula: "good_condition_device_count / in_service_device_count * 100%",
    numerator: "完好设备台数",
    denominator: "在用设备总台数",
    unit: "%",
    grain: "hospital+device_category+snapshot_date",
    dimensions: ["医院", "设备类别", "科室", "日期"],
    sources: ["设备管理系统", "设备资产台账", "物联网"],
    owner: "医学装备部",
    evidence: "industry",
    readiness: "deferred",
    audience: ["equipment"],
    version: HOSPITAL_METRIC_CATALOG_VERSION,
    validation: "排除报废、待报废和借出设备；备用但功能完好可计入分子和分母。",
    decision: "按工作簿备注不进入院长模板；它是台数时点指标，不等于单机可用率。",
  },
  {
    sourceItem: 13,
    code: "hospital.device.fault_downtime_hours",
    name: "故障停机时间",
    dimension: "reliability",
    definition: "从故障发生到修复验收合格并恢复可用的累计时长，含诊断、等待备件和实际维修，不含计划保养、校准与年检。",
    formula: "SUM(restored_at - fault_started_at)",
    numerator: "故障不可用区间总时长",
    denominator: "—",
    unit: "小时",
    grain: "hospital+device+fault_event+period",
    dimensions: ["医院", "设备", "科室", "故障类型", "月份"],
    sources: ["维修工单", "设备日志", "设备管理系统"],
    owner: "医学装备部",
    evidence: "partial",
    readiness: "ready",
    audience: ["leadership", "operations", "equipment"],
    version: HOSPITAL_METRIC_CATALOG_VERSION,
    validation: "计划停机单独分类；重复工单合并；以恢复验收时点结束。",
    decision: "与平台现有停机时长一致，增加等待备件和计划停机排除规则。",
  },
  {
    sourceItem: 14,
    code: "hospital.device.avg_repair_response_hours",
    name: "平均维修响应时间",
    dimension: "reliability",
    definition: "报修到维修人员到达或远程正式响应之间的平均时长。",
    formula: "AVG(first_response_at - reported_at)",
    numerator: "各工单响应时长之和",
    denominator: "有效维修工单数",
    unit: "小时",
    grain: "hospital+device+repair_order+period",
    dimensions: ["医院", "设备", "科室", "服务商", "故障等级", "月份"],
    sources: ["维修工单/CMMS"],
    owner: "医学装备部/服务商管理",
    evidence: "industry",
    readiness: "configure",
    audience: ["equipment"],
    version: HOSPITAL_METRIC_CATALOG_VERSION,
    validation: "明确现场到达与远程响应；撤销、重复和测试工单不计。",
    decision: "与 MTTR 拆成两个指标，避免把响应效率和修复效率混在一起。",
  },
  {
    sourceItem: 14,
    code: "hospital.device.mttr_hours",
    name: "平均修复时间（MTTR）",
    dimension: "reliability",
    definition: "已修复故障从报修/故障发生到修复验收并恢复可用的平均时长。",
    formula: "SUM(restored_at - fault_started_at) / repaired_fault_count",
    numerator: "已修复故障总修复时长",
    denominator: "已修复故障数",
    unit: "小时",
    grain: "hospital+device+fault_event+period",
    dimensions: ["医院", "设备", "科室", "服务商", "故障类型", "月份"],
    sources: ["维修工单/CMMS", "设备日志"],
    owner: "医学装备部",
    evidence: "industry",
    readiness: "ready",
    audience: ["operations", "equipment"],
    version: HOSPITAL_METRIC_CATALOG_VERSION,
    validation: "仅统计已修复故障；统一起始时点；未结工单进入在修队列但不进入平均值。",
    decision: "沿用平台现有 MTTR，并补齐工单状态和起始时点规则。",
  },
  {
    sourceItem: 15,
    code: "hospital.device.repair_cost_to_original_value_rate",
    name: "维修费用率（原值口径）",
    dimension: "reliability",
    definition: "日常维修和大修费用相对设备固定资产原值的比例，不含维保合同费用。",
    formula: "repair_cost / asset_original_value * 100%",
    numerator: "维修费用（不含维保）",
    denominator: "设备固定资产原值",
    unit: "%",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "科室", "维修类型", "月份"],
    sources: ["财务/HRP", "维修工单", "设备资产台账"],
    owner: "财务部/医学装备部",
    evidence: "partial",
    readiness: "configure",
    audience: ["leadership", "equipment"],
    version: HOSPITAL_METRIC_CATALOG_VERSION,
    validation: "维修与维保严格拆分；资本化大修按财务规则处理；原值不含后续重复入账。",
    decision: "作为资产老化与更新论证指标，和收入口径分别展示。",
  },
  {
    sourceItem: 15,
    code: "hospital.device.repair_cost_to_revenue_rate",
    name: "维修费用率（收入口径）",
    dimension: "reliability",
    definition: "日常维修和大修费用相对设备直接收入的比例，不含维保合同费用。",
    formula: "repair_cost / net_direct_revenue * 100%",
    numerator: "维修费用（不含维保）",
    denominator: "设备直接收入净额",
    unit: "%",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "科室", "月份"],
    sources: ["财务/HRP", "维修工单", "HIS/收费"],
    owner: "财务部/医学装备部",
    evidence: "partial",
    readiness: "configure",
    audience: ["leadership", "operations", "equipment"],
    version: HOSPITAL_METRIC_CATALOG_VERSION,
    validation: "分母为 0 或负数时不计算比例；维修和收入使用相同期间与设备归属。",
    decision: "用于经营负担分析，不能与原值口径共用同一个“维修费用率”标签。",
  },
  {
    sourceItem: 16,
    code: "hospital.device.fault_downtime_rate",
    name: "故障停机率",
    dimension: "reliability",
    definition: "计划可服务时段中因故障不可用的时长占比。",
    formula: "fault_downtime_hours / scheduled_service_hours * 100%",
    numerator: "故障停机时长",
    denominator: "计划可服务时长",
    unit: "%",
    grain: "hospital+device+period",
    dimensions: ["医院", "设备", "科室", "月份"],
    sources: ["设备日志", "维修工单", "排班计划"],
    owner: "医学装备部/运营部",
    evidence: "partial",
    readiness: "configure",
    audience: ["leadership", "operations", "equipment"],
    version: HOSPITAL_METRIC_CATALOG_VERSION,
    validation: "分母按设备排班确定；24×日历日只适用于明确 24 小时待命设备；计划停机不进分子。",
    decision: "不采用“1−完好率”或“1−开机率”作为默认等价公式，这三者统计对象不同。",
  },
  {
    sourceItem: 17,
    code: "hospital.device.large_equipment_positive_rate",
    name: "大型医用设备检查阳性率",
    dimension: "quality",
    definition: "适用大型检查设备中，阳性或疑似阳性的有效检查报告数占同期去重有效检查人次的比例，剔除体检。",
    formula: "positive_or_suspected_report_count / eligible_exam_count * 100%",
    numerator: "阳性或疑似阳性有效报告数",
    denominator: "同期适用大型设备去重检查人次",
    unit: "%",
    grain: "hospital+equipment_class+examId+period",
    dimensions: ["医院", "甲/乙类设备", "设备类别", "设备", "科室", "项目", "主部位", "月份"],
    sources: ["PACS/RIS", "HIS", "设备配置分类"],
    owner: "医务处/质控办/影像科",
    evidence: "direct",
    readiness: "ready",
    audience: ["leadership", "quality"],
    version: HOSPITAL_METRIC_CATALOG_VERSION,
    validation: "分子分母使用同一适用范围；多部位只计一次；体检和不适用设备类别剔除；不得跨类别直接排名。",
    decision: "作为首批核心质量指标；LIS 只能用于补充验证，不替代影像报告阳性判定。",
  },
] as const;

export const hospitalMetricSourceCoverage = Array.from(
  new Set(hospitalMetricCatalog.map((item) => item.sourceItem)),
).sort((left, right) => left - right);

export function hospitalMetricReadinessSummary() {
  return hospitalMetricCatalog.reduce(
    (summary, item) => ({ ...summary, [item.readiness]: summary[item.readiness] + 1 }),
    { ready: 0, configure: 0, deferred: 0 },
  );
}

export function hospitalMetricEvidenceSummary() {
  const sourceEvidence = new Map<number, HospitalMetricEvidence>();
  const rank: Record<HospitalMetricEvidence, number> = { incomplete: 0, industry: 1, partial: 2, direct: 3 };
  for (const item of hospitalMetricCatalog) {
    const current = sourceEvidence.get(item.sourceItem);
    if (!current || rank[item.evidence] > rank[current]) sourceEvidence.set(item.sourceItem, item.evidence);
  }
  return [...sourceEvidence.values()].reduce(
    (summary, evidence) => ({ ...summary, [evidence]: summary[evidence] + 1 }),
    { direct: 0, partial: 0, industry: 0, incomplete: 0 },
  );
}
