export type DeviceStatus = "运行良好" | "需要关注" | "效益预警";

export type CostBreakdown = {
  labor: number;
  consumables: number;
  depreciation: number;
  maintenance: number;
  energy: number;
  space: number;
  indirect: number;
};

export type Device = {
  id: string;
  assetCode: string;
  name: string;
  shortName: string;
  model: string;
  category?: string;
  manufacturer?: string;
  serialNumber?: string;
  department: string;
  /** 资产归属科室（唯一）。老数据没有时回落到 department。 */
  owningDepartment?: string;
  /** 使用科室，可多个；台账表格折叠显示。老数据没有时回落到 department。 */
  usingDepartments?: string[];
  /** 设备安放的房间号。 */
  roomNumber?: string;
  /** 该台设备的数据来源：手动填写 / 文件导入 / 接口对接。 */
  dataSource?: string;
  /** 各院自定义台账字段的值，键为 LedgerFieldDefinition.key。 */
  customFields?: Record<string, string>;
  location?: string;
  enabledDate: string;
  fundingSource?: string;
  usefulLifeYears?: number;
  depreciationMethod?: string;
  licenseNumber?: string;
  maintenanceStatus?: string;
  monitoringStatus?: string;
  investment: number;
  quantity: number;
  serviceVolume: number;
  serviceUnit: string;
  revenue: number;
  utilization: number;
  planPayback: number;
  forecastPayback: number;
  status: DeviceStatus;
  cost: CostBreakdown;
};

export type ModuleSize = "small" | "medium" | "wide" | "full";

export type ModuleHeight = "compact" | "standard" | "tall";

export type DashboardModule = {
  id: string;
  name: string;
  description: string;
  visible: boolean;
  size: ModuleSize;
  height?: ModuleHeight;
};

export type CostEntry = {
  id: string;
  type: "人工" | "耗材";
  deviceId: string;
  deviceName: string;
  item: string;
  detail: string;
  period: string;
  amount: number;
  owner: string;
  createdAt: string;
};

export type DataSource = {
  name: string;
  category: string;
  fields: string;
  owner: string;
  frequency: string;
  status: "已连接" | "待配置" | "人工填报";
  lastSync: string;
};

export const initialDevices: Device[] = [
  {
    id: "mri-01",
    assetCode: "YLSB-2021-0036",
    name: "3.0T 磁共振成像系统",
    shortName: "3.0T 磁共振",
    model: "MAGNETOM Vida",
    category: "诊断类（放射）",
    manufacturer: "西门子医疗",
    serialNumber: "MRI-VDA-20210318",
    department: "医学影像科",
    location: "医技楼二层 MR1 机房",
    enabledDate: "2021-03-18",
    fundingSource: "自筹资金",
    usefulLifeYears: 10,
    depreciationMethod: "平均年限法",
    licenseNumber: "乙类大型设备配置许可证",
    maintenanceStatus: "全保合同",
    monitoringStatus: "运行状态文件待导入",
    investment: 1580,
    quantity: 1,
    serviceVolume: 23450,
    serviceUnit: "检查人次",
    revenue: 1832,
    utilization: 83,
    planPayback: 4,
    forecastPayback: 4.5,
    status: "运行良好",
    cost: { labor: 306, consumables: 186, depreciation: 159, maintenance: 239, energy: 120, space: 106, indirect: 213 },
  },
  {
    id: "ct-01",
    assetCode: "YLSB-2022-0018",
    name: "128 排螺旋 CT",
    shortName: "128 排 CT",
    model: "Revolution CT",
    category: "诊断类（放射）",
    manufacturer: "GE 医疗",
    serialNumber: "CT-REV-20220610",
    department: "医学影像科",
    location: "门诊楼一层 CT2 机房",
    enabledDate: "2022-06-10",
    fundingSource: "财政专项 60% + 自筹 40%",
    usefulLifeYears: 10,
    depreciationMethod: "平均年限法",
    licenseNumber: "乙类大型设备配置许可证",
    maintenanceStatus: "全保合同",
    monitoringStatus: "采集器 + OCR 已接入",
    investment: 980,
    quantity: 1,
    serviceVolume: 42120,
    serviceUnit: "检查人次",
    revenue: 1550,
    utilization: 91,
    planPayback: 3,
    forecastPayback: 3.4,
    status: "运行良好",
    cost: { labor: 235, consumables: 190, depreciation: 123, maintenance: 179, energy: 134, space: 78, indirect: 181 },
  },
  {
    id: "robot-01",
    assetCode: "YLSB-2023-0007",
    name: "腔镜手术机器人",
    shortName: "手术机器人",
    model: "da Vinci Xi",
    category: "手术治疗类",
    manufacturer: "Intuitive Surgical",
    serialNumber: "DVXI-20230208",
    department: "手术部",
    location: "手术中心 8 号手术间",
    enabledDate: "2023-02-08",
    fundingSource: "医院自筹",
    usefulLifeYears: 8,
    depreciationMethod: "平均年限法",
    licenseNumber: "院内准入备案完整",
    maintenanceStatus: "原厂维保",
    monitoringStatus: "工单系统已接入",
    investment: 2200,
    quantity: 1,
    serviceVolume: 820,
    serviceUnit: "手术台次",
    revenue: 1480,
    utilization: 48,
    planPayback: 6,
    forecastPayback: 8.6,
    status: "效益预警",
    cost: { labor: 314, consumables: 513, depreciation: 215, maintenance: 248, energy: 83, space: 99, indirect: 183 },
  },
  {
    id: "linac-01",
    assetCode: "YLSB-2020-0051",
    name: "医用直线加速器",
    shortName: "直线加速器",
    model: "TrueBeam STx",
    category: "治疗类（放疗）",
    manufacturer: "瓦里安医疗",
    serialNumber: "TBSTX-20201126",
    department: "放疗科",
    location: "肿瘤中心负一层加速器机房",
    enabledDate: "2020-11-26",
    fundingSource: "专项债 + 自筹",
    usefulLifeYears: 10,
    depreciationMethod: "平均年限法",
    licenseNumber: "放射诊疗许可有效",
    maintenanceStatus: "全保合同",
    monitoringStatus: "设备日志已接入",
    investment: 1800,
    quantity: 1,
    serviceVolume: 16800,
    serviceUnit: "治疗例次",
    revenue: 2100,
    utilization: 76,
    planPayback: 5,
    forecastPayback: 5.2,
    status: "需要关注",
    cost: { labor: 379, consumables: 190, depreciation: 174, maintenance: 300, energy: 205, space: 126, indirect: 206 },
  },
  {
    id: "ultrasound-01",
    assetCode: "YLSB-2024-0023",
    name: "高端彩色多普勒超声",
    shortName: "高端超声",
    model: "EPIQ Elite",
    category: "诊断类（超声）",
    manufacturer: "飞利浦医疗",
    serialNumber: "US-EPIQ-20240115",
    department: "超声医学科",
    location: "门诊楼三层超声中心",
    enabledDate: "2024-01-15",
    fundingSource: "医院自筹",
    usefulLifeYears: 8,
    depreciationMethod: "平均年限法",
    licenseNumber: "院内验收备案完整",
    maintenanceStatus: "保修期内",
    monitoringStatus: "影像业务文件待导入",
    investment: 320,
    quantity: 2,
    serviceVolume: 32600,
    serviceUnit: "检查人次",
    revenue: 980,
    utilization: 88,
    planPayback: 2,
    forecastPayback: 2.3,
    status: "运行良好",
    cost: { labor: 270, consumables: 85, depreciation: 64, maintenance: 71, energy: 36, space: 57, indirect: 127 },
  },
  {
    id: "bio-01",
    assetCode: "YLSB-2022-0072",
    name: "全自动生化分析仪",
    shortName: "生化分析仪",
    model: "cobas pro",
    category: "检验类",
    manufacturer: "罗氏诊断",
    serialNumber: "LIS-CBP-20220903",
    department: "检验科",
    location: "检验科生化流水线区",
    enabledDate: "2022-09-03",
    fundingSource: "医院自筹",
    usefulLifeYears: 8,
    depreciationMethod: "平均年限法",
    licenseNumber: "院内验收备案完整",
    maintenanceStatus: "试剂绑定维保",
    monitoringStatus: "检验业务文件待导入",
    investment: 450,
    quantity: 1,
    serviceVolume: 450000,
    serviceUnit: "检测项次",
    revenue: 1220,
    utilization: 79,
    planPayback: 2.5,
    forecastPayback: 3,
    status: "运行良好",
    cost: { labor: 194, consumables: 349, depreciation: 78, maintenance: 107, energy: 68, space: 49, indirect: 125 },
  },
  {
    id: "mri-02",
    assetCode: "YLSB-2023-0012",
    name: "3.0T 磁共振成像系统（二号机）",
    shortName: "3.0T 磁共振 2 号",
    model: "uMR 780",
    category: "诊断类（放射）",
    manufacturer: "联影医疗",
    serialNumber: "MRI-UMR-20230415",
    department: "医学影像科",
    location: "医技楼二层 MR2 机房",
    enabledDate: "2023-04-15",
    fundingSource: "财政专项 50% + 自筹 50%",
    usefulLifeYears: 10,
    depreciationMethod: "平均年限法",
    licenseNumber: "乙类大型设备配置许可证",
    maintenanceStatus: "全保合同",
    monitoringStatus: "设备日志已接入",
    investment: 1480,
    quantity: 1,
    serviceVolume: 21800,
    serviceUnit: "检查人次",
    revenue: 1635,
    utilization: 81,
    planPayback: 4,
    forecastPayback: 4.2,
    status: "运行良好",
    cost: { labor: 288, consumables: 165, depreciation: 148, maintenance: 118, energy: 112, space: 92, indirect: 188 },
  },
  {
    id: "mri-03",
    assetCode: "YLSB-2018-0044",
    name: "1.5T 磁共振成像系统",
    shortName: "1.5T 磁共振",
    model: "MAGNETOM Aera",
    category: "诊断类（放射）",
    manufacturer: "西门子医疗",
    serialNumber: "MRI-AER-20181022",
    department: "医学影像科",
    location: "住院楼负一层 MR3 机房",
    enabledDate: "2018-10-22",
    fundingSource: "自筹资金",
    usefulLifeYears: 10,
    depreciationMethod: "平均年限法",
    licenseNumber: "乙类大型设备配置许可证",
    maintenanceStatus: "脱保",
    monitoringStatus: "运行状态文件待导入",
    investment: 920,
    quantity: 1,
    serviceVolume: 19400,
    serviceUnit: "检查人次",
    revenue: 1010,
    utilization: 72,
    planPayback: 5,
    forecastPayback: 6.8,
    status: "需要关注",
    cost: { labor: 236, consumables: 118, depreciation: 92, maintenance: 64, energy: 86, space: 71, indirect: 142 },
  },
  {
    id: "ct-02",
    assetCode: "YLSB-2024-0009",
    name: "256 排宽体螺旋 CT",
    shortName: "256 排 CT",
    model: "Revolution Apex",
    category: "诊断类（放射）",
    manufacturer: "GE 医疗",
    serialNumber: "CT-APX-20240322",
    department: "医学影像科",
    location: "门诊楼一层 CT1 机房",
    enabledDate: "2024-03-22",
    fundingSource: "财政专项 60% + 自筹 40%",
    usefulLifeYears: 10,
    depreciationMethod: "平均年限法",
    licenseNumber: "乙类大型设备配置许可证",
    maintenanceStatus: "全保合同",
    monitoringStatus: "采集器 + OCR 已接入",
    investment: 2050,
    quantity: 1,
    serviceVolume: 49600,
    serviceUnit: "检查人次",
    revenue: 1885,
    utilization: 93,
    planPayback: 4,
    forecastPayback: 4.4,
    status: "运行良好",
    cost: { labor: 262, consumables: 214, depreciation: 205, maintenance: 143, energy: 152, space: 84, indirect: 196 },
  },
  {
    id: "ct-03",
    assetCode: "YLSB-2021-0058",
    name: "64 排螺旋 CT（急诊）",
    shortName: "64 排 CT",
    model: "Aquilion Prime SP",
    category: "诊断类（放射）",
    manufacturer: "佳能医疗",
    serialNumber: "CT-AQP-20210906",
    department: "医学影像科",
    location: "急诊楼一层急诊 CT 机房",
    enabledDate: "2021-09-06",
    fundingSource: "医院自筹",
    usefulLifeYears: 10,
    depreciationMethod: "平均年限法",
    licenseNumber: "乙类大型设备配置许可证",
    maintenanceStatus: "第三方维保",
    monitoringStatus: "设备日志已接入",
    investment: 760,
    quantity: 1,
    serviceVolume: 36400,
    serviceUnit: "检查人次",
    revenue: 1130,
    utilization: 88,
    planPayback: 3.5,
    forecastPayback: 3.8,
    status: "运行良好",
    cost: { labor: 224, consumables: 158, depreciation: 84, maintenance: 53, energy: 108, space: 62, indirect: 139 },
  },
  {
    id: "dr-01",
    assetCode: "YLSB-2022-0031",
    name: "数字化 X 线摄影系统（门诊）",
    shortName: "DR 1 号",
    model: "DigitalDiagnost C90",
    category: "诊断类（放射）",
    manufacturer: "飞利浦医疗",
    serialNumber: "DR-DDC-20220518",
    department: "医学影像科",
    location: "门诊楼二层 DR1 摄片室",
    enabledDate: "2022-05-18",
    fundingSource: "医院自筹",
    usefulLifeYears: 8,
    depreciationMethod: "平均年限法",
    licenseNumber: "院内验收备案完整",
    maintenanceStatus: "第三方维保",
    monitoringStatus: "影像业务文件待导入",
    investment: 185,
    quantity: 1,
    serviceVolume: 51600,
    serviceUnit: "检查人次",
    revenue: 402,
    utilization: 86,
    planPayback: 2,
    forecastPayback: 2.2,
    status: "运行良好",
    cost: { labor: 132, consumables: 26, depreciation: 23, maintenance: 9, energy: 14, space: 18, indirect: 46 },
  },
  {
    id: "dr-02",
    assetCode: "YLSB-2022-0032",
    name: "数字化 X 线摄影系统（住院部）",
    shortName: "DR 2 号",
    model: "uDR 780i",
    category: "诊断类（放射）",
    manufacturer: "联影医疗",
    serialNumber: "DR-UDR-20220627",
    department: "医学影像科",
    location: "住院楼一层 DR2 摄片室",
    enabledDate: "2022-06-27",
    fundingSource: "医院自筹",
    usefulLifeYears: 8,
    depreciationMethod: "平均年限法",
    licenseNumber: "院内验收备案完整",
    maintenanceStatus: "第三方维保",
    monitoringStatus: "影像业务文件待导入",
    investment: 168,
    quantity: 1,
    serviceVolume: 43900,
    serviceUnit: "检查人次",
    revenue: 334,
    utilization: 79,
    planPayback: 2,
    forecastPayback: 2.6,
    status: "运行良好",
    cost: { labor: 121, consumables: 22, depreciation: 21, maintenance: 8, energy: 12, space: 15, indirect: 40 },
  },
  {
    id: "dr-03",
    assetCode: "YLSB-2024-0041",
    name: "数字化 X 线摄影系统（体检中心）",
    shortName: "DR 3 号",
    model: "新东方 1000T",
    category: "诊断类（放射）",
    manufacturer: "万东医疗",
    serialNumber: "DR-XDF-20240520",
    department: "健康管理中心",
    location: "体检楼二层摄片室",
    enabledDate: "2024-05-20",
    fundingSource: "医院自筹",
    usefulLifeYears: 8,
    depreciationMethod: "平均年限法",
    licenseNumber: "院内验收备案完整",
    maintenanceStatus: "保修期内",
    monitoringStatus: "影像业务文件待导入",
    investment: 152,
    quantity: 1,
    serviceVolume: 11800,
    serviceUnit: "检查人次",
    revenue: 94,
    utilization: 46,
    planPayback: 3,
    forecastPayback: 12,
    status: "效益预警",
    cost: { labor: 58, consumables: 8, depreciation: 17, maintenance: 3, energy: 6, space: 11, indirect: 17 },
  },
  {
    id: "dr-mobile-01",
    assetCode: "YLSB-2019-0027",
    name: "移动式数字化 X 线摄影系统",
    shortName: "移动 DR",
    model: "MobileDiagnost wDR",
    category: "诊断类（放射）",
    manufacturer: "飞利浦医疗",
    serialNumber: "DR-MOB-20190712",
    department: "重症医学科",
    location: "ICU 病区床旁（流动）",
    enabledDate: "2019-07-12",
    fundingSource: "自筹资金",
    usefulLifeYears: 8,
    depreciationMethod: "平均年限法",
    licenseNumber: "院内验收备案完整",
    maintenanceStatus: "脱保",
    monitoringStatus: "扫码登记已启用",
    investment: 132,
    quantity: 1,
    serviceVolume: 9200,
    serviceUnit: "检查人次",
    revenue: 83,
    utilization: 58,
    planPayback: 4,
    forecastPayback: 9.5,
    status: "需要关注",
    cost: { labor: 44, consumables: 5, depreciation: 17, maintenance: 6, energy: 2, space: 2, indirect: 9 },
  },
  {
    id: "dsa-01",
    assetCode: "YLSB-2022-0049",
    name: "数字减影血管造影系统（DSA）",
    shortName: "DSA",
    model: "Azurion 7 M20",
    category: "手术治疗类（介入）",
    manufacturer: "飞利浦医疗",
    serialNumber: "DSA-AZ7-20221108",
    department: "介入医学科",
    location: "介入中心一层 1 号导管室",
    enabledDate: "2022-11-08",
    fundingSource: "专项债 + 自筹",
    usefulLifeYears: 10,
    depreciationMethod: "平均年限法",
    licenseNumber: "乙类大型设备配置许可证",
    maintenanceStatus: "原厂维保",
    monitoringStatus: "手术业务文件待导入",
    investment: 1380,
    quantity: 1,
    serviceVolume: 2680,
    serviceUnit: "手术台次",
    revenue: 1340,
    utilization: 74,
    planPayback: 5,
    forecastPayback: 5.4,
    status: "运行良好",
    cost: { labor: 246, consumables: 262, depreciation: 138, maintenance: 97, energy: 76, space: 88, indirect: 158 },
  },
  {
    id: "us-02",
    assetCode: "YLSB-2023-0035",
    name: "高端彩色多普勒超声（心脏专用）",
    shortName: "心脏彩超",
    model: "EPIQ CVx",
    category: "诊断类（超声）",
    manufacturer: "飞利浦医疗",
    serialNumber: "US-CVX-20230814",
    department: "超声医学科",
    location: "门诊楼三层心脏超声室",
    enabledDate: "2023-08-14",
    fundingSource: "医院自筹",
    usefulLifeYears: 8,
    depreciationMethod: "平均年限法",
    licenseNumber: "院内验收备案完整",
    maintenanceStatus: "原厂维保",
    monitoringStatus: "影像业务文件待导入",
    investment: 295,
    quantity: 1,
    serviceVolume: 20600,
    serviceUnit: "检查人次",
    revenue: 620,
    utilization: 84,
    planPayback: 2.5,
    forecastPayback: 2.4,
    status: "运行良好",
    cost: { labor: 176, consumables: 38, depreciation: 37, maintenance: 21, energy: 12, space: 24, indirect: 67 },
  },
  {
    id: "us-03",
    assetCode: "YLSB-2024-0016",
    name: "高端彩色多普勒超声（妇产专用）",
    shortName: "妇产彩超",
    model: "Voluson E10",
    category: "诊断类（超声）",
    manufacturer: "GE 医疗",
    serialNumber: "US-VE10-20240226",
    department: "超声医学科",
    location: "妇产科门诊超声室",
    enabledDate: "2024-02-26",
    fundingSource: "医院自筹",
    usefulLifeYears: 8,
    depreciationMethod: "平均年限法",
    licenseNumber: "院内验收备案完整",
    maintenanceStatus: "保修期内",
    monitoringStatus: "影像业务文件待导入",
    investment: 268,
    quantity: 1,
    serviceVolume: 23900,
    serviceUnit: "检查人次",
    revenue: 645,
    utilization: 87,
    planPayback: 2,
    forecastPayback: 2,
    status: "运行良好",
    cost: { labor: 182, consumables: 41, depreciation: 34, maintenance: 19, energy: 11, space: 22, indirect: 64 },
  },
  {
    id: "us-portable-01",
    assetCode: "YLSB-2024-0052",
    name: "便携式彩色多普勒超声",
    shortName: "便携彩超",
    model: "Venue Go",
    category: "诊断类（超声）",
    manufacturer: "GE 医疗",
    serialNumber: "US-VNG-20240618",
    department: "重症医学科",
    location: "ICU 病区床旁（流动）",
    enabledDate: "2024-06-18",
    fundingSource: "医院自筹",
    usefulLifeYears: 6,
    depreciationMethod: "平均年限法",
    licenseNumber: "院内验收备案完整",
    maintenanceStatus: "保修期内",
    monitoringStatus: "扫码登记已启用",
    investment: 88,
    quantity: 1,
    serviceVolume: 5400,
    serviceUnit: "检查人次",
    revenue: 62,
    utilization: 52,
    planPayback: 4,
    forecastPayback: 13,
    status: "效益预警",
    cost: { labor: 39, consumables: 5, depreciation: 11, maintenance: 4, energy: 1, space: 2, indirect: 8 },
  },
  {
    id: "endo-gastro-01",
    assetCode: "YLSB-2023-0021",
    name: "电子胃镜系统",
    shortName: "电子胃镜",
    model: "EVIS X1 CV-1500",
    category: "诊断类（内镜）",
    manufacturer: "奥林巴斯",
    serialNumber: "EN-GAS-20230530",
    department: "消化内镜中心",
    location: "内镜中心 3 号诊室",
    enabledDate: "2023-05-30",
    fundingSource: "医院自筹",
    usefulLifeYears: 8,
    depreciationMethod: "平均年限法",
    licenseNumber: "院内验收备案完整",
    maintenanceStatus: "原厂维保",
    monitoringStatus: "内镜业务文件待导入",
    investment: 342,
    quantity: 1,
    serviceVolume: 13200,
    serviceUnit: "检查人次",
    revenue: 570,
    utilization: 82,
    planPayback: 3,
    forecastPayback: 3.1,
    status: "运行良好",
    cost: { labor: 164, consumables: 92, depreciation: 43, maintenance: 24, energy: 9, space: 21, indirect: 55 },
  },
  {
    id: "endo-colon-01",
    assetCode: "YLSB-2023-0022",
    name: "电子结肠镜系统",
    shortName: "电子肠镜",
    model: "EVIS X1 CF-EZ1500",
    category: "诊断类（内镜）",
    manufacturer: "奥林巴斯",
    serialNumber: "EN-COL-20230530",
    department: "消化内镜中心",
    location: "内镜中心 5 号诊室",
    enabledDate: "2023-05-30",
    fundingSource: "医院自筹",
    usefulLifeYears: 8,
    depreciationMethod: "平均年限法",
    licenseNumber: "院内验收备案完整",
    maintenanceStatus: "原厂维保",
    monitoringStatus: "内镜业务文件待导入",
    investment: 315,
    quantity: 1,
    serviceVolume: 9800,
    serviceUnit: "检查人次",
    revenue: 490,
    utilization: 78,
    planPayback: 3,
    forecastPayback: 3.6,
    status: "运行良好",
    cost: { labor: 148, consumables: 84, depreciation: 39, maintenance: 22, energy: 8, space: 20, indirect: 49 },
  },
  {
    id: "lap-01",
    assetCode: "YLSB-2022-0064",
    name: "4K 腹腔镜手术系统",
    shortName: "4K 腹腔镜",
    model: "VISERA ELITE III",
    category: "手术治疗类",
    manufacturer: "奥林巴斯",
    serialNumber: "LAP-VE3-20221215",
    department: "手术部",
    location: "手术中心 5 号手术间",
    enabledDate: "2022-12-15",
    fundingSource: "医院自筹",
    usefulLifeYears: 8,
    depreciationMethod: "平均年限法",
    licenseNumber: "院内准入备案完整",
    maintenanceStatus: "第三方维保",
    monitoringStatus: "手术业务文件待导入",
    investment: 276,
    quantity: 1,
    serviceVolume: 1520,
    serviceUnit: "手术台次",
    revenue: 640,
    utilization: 76,
    planPayback: 3.5,
    forecastPayback: 3.7,
    status: "运行良好",
    cost: { labor: 156, consumables: 187, depreciation: 35, maintenance: 19, energy: 7, space: 26, indirect: 62 },
  },
  {
    id: "hema-01",
    assetCode: "YLSB-2023-0056",
    name: "血液分析流水线",
    shortName: "血液流水线",
    model: "XN-9100",
    category: "检验类",
    manufacturer: "希森美康",
    serialNumber: "LIS-XN9-20230911",
    department: "检验科",
    location: "检验科血液体液区",
    enabledDate: "2023-09-11",
    fundingSource: "医院自筹",
    usefulLifeYears: 8,
    depreciationMethod: "平均年限法",
    licenseNumber: "院内验收备案完整",
    maintenanceStatus: "试剂绑定维保",
    monitoringStatus: "检验业务文件待导入",
    investment: 435,
    quantity: 1,
    serviceVolume: 268000,
    serviceUnit: "标本数",
    revenue: 670,
    utilization: 76,
    planPayback: 3,
    forecastPayback: 3.5,
    status: "运行良好",
    cost: { labor: 128, consumables: 196, depreciation: 54, maintenance: 30, energy: 24, space: 18, indirect: 66 },
  },
  {
    id: "vent-01",
    assetCode: "YLSB-2021-0072",
    name: "有创呼吸机组（生命支持）",
    shortName: "呼吸机组",
    model: "SV800 / Evita V300 混编",
    category: "生命支持类",
    manufacturer: "迈瑞医疗 / 德尔格",
    serialNumber: "ICU-VENT-2021 批次",
    department: "重症医学科",
    location: "ICU 一、二病区",
    enabledDate: "2021-12-20",
    fundingSource: "财政专项",
    usefulLifeYears: 8,
    depreciationMethod: "平均年限法",
    licenseNumber: "院内验收备案完整",
    maintenanceStatus: "原厂维保",
    monitoringStatus: "扫码登记已启用",
    investment: 340,
    quantity: 20,
    serviceVolume: 5900,
    serviceUnit: "机械通气日",
    revenue: 205,
    utilization: 63,
    planPayback: 6,
    forecastPayback: 8.8,
    status: "需要关注",
    cost: { labor: 68, consumables: 48, depreciation: 38, maintenance: 20, energy: 6, space: 5, indirect: 21 },
  },
];

export const initialModules: DashboardModule[] = [
  { id: "kpi", name: "核心指标", description: "投资、收入、净收益、使用率与预警数", visible: true, size: "full" },
  { id: "dimensions", name: "五维效益评价", description: "经济、效率、质量、体验与设备保障综合评分", visible: true, size: "full" },
  { id: "trend", name: "收入成本趋势", description: "月度收入、成本与净收益趋势", visible: true, size: "wide" },
  { id: "cost", name: "成本构成", description: "人工、耗材、折旧、维保等成本占比", visible: true, size: "small" },
  { id: "payback", name: "回本年限对比", description: "原计划与最新预计回本周期", visible: true, size: "medium" },
  { id: "efficiency", name: "效益效率矩阵", description: "使用率与投资收益率四象限", visible: true, size: "medium" },
  { id: "quality", name: "质量与患者体验", description: "报告质控、重复检查、等待与报告时效", visible: true, size: "medium" },
  { id: "reliability", name: "设备保障", description: "可用率、故障、停机与预防性维护", visible: true, size: "medium" },
  { id: "workforce", name: "人员绩效", description: "技师、诊断医生工作量与科室绩效质控", visible: true, size: "full" },
  { id: "category", name: "品类经营与资源配置", description: "同类横比、收益排行与共享潜力", visible: true, size: "full" },
  { id: "alerts", name: "管理预警", description: "低使用率、亏损和回本延期提示", visible: true, size: "small" },
  { id: "table", name: "设备效益明细", description: "按单机查看收入、成本、服务量和状态", visible: true, size: "full" },
  { id: "hospital-compare", name: "集团医院对比", description: "同集团医院核心效益指标横向对比", visible: false, size: "full" },
];

export const initialCostEntries: CostEntry[] = [
  { id: "ce-01", type: "人工", deviceId: "mri-01", deviceName: "3.0T 磁共振成像系统", item: "影像技师", detail: "6 人 × 160 小时 × 186 元/小时", period: "2026-06", amount: 17.86, owner: "医学影像科", createdAt: "2026-07-02 09:20" },
  { id: "ce-02", type: "耗材", deviceId: "robot-01", deviceName: "腔镜手术机器人", item: "专用器械臂耗材", detail: "41 套 × 12,500 元/套 · 单独收费", period: "2026-06", amount: 51.25, owner: "手术部", createdAt: "2026-07-03 14:35" },
  { id: "ce-03", type: "耗材", deviceId: "bio-01", deviceName: "全自动生化分析仪", item: "生化检测试剂", detail: "126 盒 × 2,760 元/盒 · 不可单独收费", period: "2026-06", amount: 34.78, owner: "检验科", createdAt: "2026-07-04 11:08" },
  { id: "ce-04", type: "人工", deviceId: "ct-02", deviceName: "256 排宽体螺旋 CT", item: "影像技师", detail: "8 人 × 168 小时 × 172 元/小时", period: "2026-07", amount: 23.11, owner: "医学影像科", createdAt: "2026-08-02 10:14" },
  { id: "ce-05", type: "耗材", deviceId: "dsa-01", deviceName: "数字减影血管造影系统（DSA）", item: "导管室介入耗材", detail: "造影导管、导丝等 126 台次领用 · 单独收费", period: "2026-07", amount: 24.58, owner: "介入医学科", createdAt: "2026-08-03 15:22" },
  { id: "ce-06", type: "耗材", deviceId: "hema-01", deviceName: "血液分析流水线", item: "血细胞分析试剂", detail: "84 套 × 3,150 元/套 · 不可单独收费", period: "2026-07", amount: 26.46, owner: "检验科", createdAt: "2026-08-04 09:41" },
  { id: "ce-07", type: "人工", deviceId: "endo-gastro-01", deviceName: "电子胃镜系统", item: "内镜医师与护士", detail: "4 人 × 152 小时 × 198 元/小时", period: "2026-07", amount: 12.04, owner: "消化内镜中心", createdAt: "2026-08-04 16:05" },
  { id: "ce-08", type: "耗材", deviceId: "vent-01", deviceName: "有创呼吸机组（生命支持）", item: "呼吸管路与细菌过滤器", detail: "486 套 × 86 元/套 · 不可单独收费", period: "2026-07", amount: 4.18, owner: "重症医学科", createdAt: "2026-08-05 08:52" },
  { id: "ce-09", type: "人工", deviceId: "dr-03", deviceName: "数字化 X 线摄影系统（体检中心）", item: "放射技师（兼班）", detail: "2 人 × 88 小时 × 165 元/小时", period: "2026-07", amount: 2.9, owner: "健康管理中心", createdAt: "2026-08-05 11:37" },
  { id: "ce-10", type: "耗材", deviceId: "mri-02", deviceName: "3.0T 磁共振成像系统（二号机）", item: "对比剂（钆剂）", detail: "612 支 × 285 元/支 · 单独收费", period: "2026-07", amount: 17.44, owner: "医学影像科", createdAt: "2026-08-06 14:19" },
];

export const dataSources: DataSource[] = [
  { name: "设备资产主数据文件", category: "设备与资产", fields: "资产编号、品牌型号、原值、启用日期、使用科室", owner: "资产部 / 设备科", frequency: "每月", status: "已连接", lastSync: "2026-07-22 月度文件" },
  { name: "收费收入文件", category: "业务与收入", fields: "收费项目、执行科室、收入、退费", owner: "信息部 / 财务部", frequency: "每日", status: "待配置", lastSync: "—" },
  { name: "影像业务文件", category: "影像设备", fields: "检查次数、设备编码、报告时效", owner: "信息部 / 影像科", frequency: "每日", status: "待配置", lastSync: "—" },
  { name: "检验业务文件", category: "检验设备", fields: "样本数、检测项次、仪器编码", owner: "信息部 / 检验科", frequency: "每日", status: "待配置", lastSync: "—" },
  { name: "内镜业务文件", category: "内镜设备", fields: "检查例次、主机编号、镜体编号与类型", owner: "内镜中心 / 信息部", frequency: "每日", status: "待配置", lastSync: "—" },
  { name: "手术业务文件", category: "手术设备", fields: "手术事件键、设备编码、使用起止时间", owner: "手术部 / 信息部", frequency: "每日", status: "待配置", lastSync: "—" },
  { name: "财务成本文件", category: "财务与成本", fields: "原值、折旧、收入、付款与凭证", owner: "财务部 / 资产部", frequency: "每月", status: "已连接", lastSync: "2026-07 月度文件" },
  { name: "耗材明细文件", category: "耗材与试剂", fields: "领用量、出库价、退库、批次", owner: "物资部 / 使用科室", frequency: "每日", status: "待配置", lastSync: "—" },
  { name: "设备运行日志文件", category: "运行状态", fields: "开机时长、故障、停机、能耗", owner: "设备科 / 信息部", frequency: "每日", status: "待配置", lastSync: "—" },
  { name: "维修保养文件", category: "设备保障", fields: "报修、故障、停机、MTTR、PM、合同与备件", owner: "医学装备部 / 采购部", frequency: "每日", status: "待配置", lastSync: "—" },
  { name: "预约排队文件", category: "患者体验", fields: "申请、预约、签到、叫号、开始与取消时间", owner: "门诊部 / 运营部 / 信息部", frequency: "每日", status: "待配置", lastSync: "—" },
  { name: "临床质控文件", category: "临床质量", fields: "报告抽检、操作质控、合理使用、疑难病例", owner: "医务处 / 质控办", frequency: "每月", status: "人工填报", lastSync: "2026-07 月度文件" },
  { name: "能源空间文件", category: "后勤资源", fields: "电水气用量、单价、设备面积、内部面积成本", owner: "后勤部 / 基建处 / 财务部", frequency: "每月", status: "人工填报", lastSync: "2026-07 月度文件" },
  { name: "人工成本文件", category: "人员投入", fields: "岗位、人数、工时、小时成本", owner: "人力资源部 / 使用科室", frequency: "每月", status: "人工填报", lastSync: "2026-07 月度文件" },
];

export const monthLabels = ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"];
export const revenueFactors = [0.8, 0.64, 0.96, 1, 1.04, 1.05, 1.1, 1.12, 1.05, 1.07, 1.06, 1.11];
export const costFactors = [0.93, 0.9, 0.97, 1, 1.01, 1.02, 1.04, 1.05, 1.02, 1.03, 1.01, 1.02];

export function cloneDevicesForHospital(hospitalId: string): Device[] {
  const profile = hospitalId === "hosp-east"
    ? { revenue: 0.74, cost: 0.71, volume: 0.72, utilization: -5 }
    : hospitalId === "hosp-specialty"
      ? { revenue: 0.58, cost: 0.61, volume: 0.56, utilization: -9 }
      : { revenue: 1, cost: 1, volume: 1, utilization: 0 };
  return initialDevices.map((device) => ({
    ...device,
    revenue: Math.round(device.revenue * profile.revenue),
    serviceVolume: Math.round(device.serviceVolume * profile.volume),
    utilization: Math.max(35, Math.min(98, device.utilization + profile.utilization)),
    forecastPayback: Number((device.forecastPayback / Math.max(profile.revenue, 0.4)).toFixed(1)),
    cost: Object.fromEntries(Object.entries(device.cost).map(([key, value]) => [key, Math.round(value * profile.cost)])) as Device["cost"],
  }));
}

export function totalCost(device: Device) {
  return Object.values(device.cost).reduce((sum, value) => sum + value, 0);
}

export function netBenefit(device: Device) {
  return device.revenue - totalCost(device);
}

export function roi(device: Device) {
  return (netBenefit(device) / device.investment) * 100;
}
