export type NotificationCategory = "预警" | "待办" | "数据" | "安全" | "系统";
export type NotificationPriority = "紧急" | "重要" | "普通";
export type NotificationTarget = "detail" | "costs" | "improvement" | "sources" | "access" | "cockpit";

export type PlatformNotification = {
  id: string;
  title: string;
  summary: string;
  detail: string;
  category: NotificationCategory;
  priority: NotificationPriority;
  hospitalId?: string;
  hospitalName: string;
  createdAt: string;
  timeLabel: string;
  source: string;
  read: boolean;
  actionLabel?: string;
  target?: NotificationTarget;
  deviceId?: string;
};

export const initialNotifications: PlatformNotification[] = [
  {
    id: "notice-robot-roi",
    title: "手术机器人进入效益预警区间",
    summary: "近 3 个月手术量低于计划 18%，预计回本期延长至 8.6 年。",
    detail: "建议医学装备部联合手术部复核术式开放、排程利用率与专用耗材成本，并在本周运营例会上确认改进负责人。",
    category: "预警",
    priority: "紧急",
    hospitalId: "hosp-central",
    hospitalName: "中心医院",
    createdAt: "2026-08-11T09:26:00+08:00",
    timeLabel: "今天 09:26",
    source: "效益预警引擎",
    read: false,
    actionLabel: "查看单机分析",
    target: "detail",
    deviceId: "robot-01",
  },
  {
    id: "notice-mri3-warranty",
    title: "1.5T 磁共振脱保运行已满 90 天",
    summary: "脱保期间发生 2 次冷头告警，按次维修均价 8.6 万元。",
    detail: "建议医学装备部完成续保比价与按次维修成本测算，纳入 9 月采购计划；续保前请提高巡检频次并同步更新设备保障口径。",
    category: "预警",
    priority: "重要",
    hospitalId: "hosp-central",
    hospitalName: "中心医院",
    createdAt: "2026-08-11T08:15:00+08:00",
    timeLabel: "今天 08:15",
    source: "设备维保文件",
    read: false,
    actionLabel: "查看设备详情",
    target: "detail",
    deviceId: "mri-03",
  },
  {
    id: "notice-cost-review",
    title: "7 月人工成本等待财务复核",
    summary: "医学影像科、消化内镜中心提交 5 条人工成本记录，共计 55.3 万元。",
    detail: "成本将在复核通过后进入正式月度口径。请核对人员范围、工时来源和小时成本版本，避免与科室间接成本重复归集。",
    category: "待办",
    priority: "重要",
    hospitalId: "hosp-central",
    hospitalName: "中心医院",
    createdAt: "2026-08-10T17:42:00+08:00",
    timeLabel: "昨天 17:42",
    source: "成本填报中心",
    read: false,
    actionLabel: "去复核成本",
    target: "costs",
  },
  {
    id: "notice-recon-diff",
    title: "门诊 DR 收费对账差异率超过阈值",
    summary: "7 月实际摄片 4,412 人次，与有效收费差异 2.4%，超过 1.5% 阈值。",
    detail: "差异明细已进入对账队列，免费复查、绿色通道与退费补录需分类说明。请医学影像科与财务部在 3 个工作日内完成核对并登记原因。",
    category: "数据",
    priority: "重要",
    hospitalId: "hosp-central",
    hospitalName: "中心医院",
    createdAt: "2026-08-10T14:05:00+08:00",
    timeLabel: "昨天 14:05",
    source: "数据质量监测",
    read: false,
    actionLabel: "检查数据源",
    target: "sources",
    deviceId: "dr-01",
  },
  {
    id: "notice-ct2-overload",
    title: "256 排 CT 预约等待升至 4.5 天",
    summary: "使用率连续 8 周超过 90%，高峰时段号源已约满。",
    detail: "建议将 20% 平扫检查分流至急诊 64 排 CT，并加开晚间增强时段；中期请医学装备部同步准备第三台 CT 配置论证数据包。",
    category: "预警",
    priority: "重要",
    hospitalId: "hosp-central",
    hospitalName: "中心医院",
    createdAt: "2026-08-10T09:12:00+08:00",
    timeLabel: "昨天 09:12",
    source: "效益预警引擎",
    read: false,
    actionLabel: "查看单机分析",
    target: "detail",
    deviceId: "ct-02",
  },
  {
    id: "notice-dr3-utilization",
    title: "体检中心 DR 使用率连续 3 个月低于 50%",
    summary: "平均单日检查量不足 20 人次，7 月账面净收益为负。",
    detail: "改进任务已立项：合并门诊时段并开放体检预约，同时评估与门诊 DR 错峰共享。请健康管理中心在本周内确认责任人与复测口径。",
    category: "待办",
    priority: "重要",
    hospitalId: "hosp-central",
    hospitalName: "中心医院",
    createdAt: "2026-08-09T16:40:00+08:00",
    timeLabel: "08-09 16:40",
    source: "运营改进中心",
    read: true,
    actionLabel: "查看改进任务",
    target: "improvement",
    deviceId: "dr-03",
  },
  {
    id: "notice-monthly-publish",
    title: "2026 年 7 月月度数据发布完成",
    summary: "22 台设备的收入、成本与服务量已冻结入库，口径版本 2026-V2.0。",
    detail: "本次发布覆盖设备资产、收费收入与财务成本三类月度文件；影像、检验业务明细仍按日增量接入。发布后口径变更需走版本化流程。",
    category: "数据",
    priority: "普通",
    hospitalId: "hosp-central",
    hospitalName: "中心医院",
    createdAt: "2026-08-08T18:30:00+08:00",
    timeLabel: "08-08 18:30",
    source: "数据发布中心",
    read: true,
    actionLabel: "检查数据源",
    target: "sources",
  },
  {
    id: "notice-metric-review",
    title: "3 项临床质量指标等待质控办复核",
    summary: "阳性率、增强率与报告合格率的 7 月人工填报值待确认。",
    detail: "人工填报指标须在每月 15 日前完成业务确认，逾期将在报表中标记为缺失。请质控办核对抽检样本量与适用项目范围后签认。",
    category: "待办",
    priority: "普通",
    hospitalId: "hosp-central",
    hospitalName: "中心医院",
    createdAt: "2026-08-08T10:20:00+08:00",
    timeLabel: "08-08 10:20",
    source: "指标治理中心",
    read: true,
    actionLabel: "检查数据源",
    target: "sources",
  },
  {
    id: "notice-access-review",
    title: "季度高风险权限复核将在 9 天后到期",
    summary: "需复核平台管理员、医院管理员、设备和财务管理员。",
    detail: "请确认离岗账号、临时授权、跨院成员关系和导出权限。复核结果应保留操作者、时间、变更前后值和审批依据。",
    category: "安全",
    priority: "紧急",
    hospitalName: "全平台",
    createdAt: "2026-08-07T09:00:00+08:00",
    timeLabel: "08-07 09:00",
    source: "安全治理中心",
    read: false,
    actionLabel: "开始权限复核",
    target: "access",
  },
  {
    id: "notice-member-review",
    title: "东院新增成员等待激活",
    summary: "1 个医学装备管理员账号已创建医院成员关系。",
    detail: "成员还需要进入站点访问名单并完成首次登录。超过 7 天未激活时，邀请应自动失效并进入安全审计。",
    category: "安全",
    priority: "重要",
    hospitalId: "hosp-east",
    hospitalName: "东院",
    createdAt: "2026-08-06T11:32:00+08:00",
    timeLabel: "08-06 11:32",
    source: "医院与权限",
    read: true,
    actionLabel: "查看账号成员",
    target: "access",
  },
  {
    id: "notice-metric-version",
    title: "2026-V2.0 指标口径已生效",
    summary: "现金贡献、简单回收期和设备可用率口径完成版本更新。",
    detail: "新版本已应用于 2026 年度分析。历史报表仍保留原口径版本号，导出时会同时携带分析期间和口径版本。",
    category: "系统",
    priority: "普通",
    hospitalName: "全平台",
    createdAt: "2026-08-01T10:15:00+08:00",
    timeLabel: "08-01 10:15",
    source: "指标治理中心",
    read: true,
    actionLabel: "查看指标口径",
    target: "sources",
  },
];
